# Generated by Django 6.1.1 on 2026-10-05 00:11

from django.db import migrations

SYSTEM_ACCOUNTS = [
    ("cash", "Platform:Cash"),
    ("external", "External:Provider"),
]

def seed_system_accounts(apps, schema_editor):
    Account = apps.get_model("ledger", "Account")
    for kind, reference in SYSTEM_ACCOUNTS:
        Account.objects.get_or_create(reference=reference, defaults={"kind": kind})

class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_system_accounts, migrations.RunPython.noop),
    ]
