# Generated by Django 6.1.1 on 2026-10-02 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payable_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='ledger.account')),
            ],
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('batched', 'Batched'), ('paid', 'Paid'), ('failed', 'Failed'), ('unresolved', 'Unresolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.transaction')),
                ('settled_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.transaction')),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='payouts.recipient')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='obligation_amount_positive')],
            },
        ),
    ]
