# Generated by Django 6.1.1 on 2026-10-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obligation',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='obligation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
